sudo: true
language: python
python:
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly" # currently points to 3.7-dev
install: 
- "pip install -q coverage"
script: 
- coverage run src/pwbs.py
- python -m unittest src/pwbs_test.py
